data/featuredstory.yml

line 13:  The rise of advance (T was missing)

Missing letter added

---

content/about/contact.md

contact details of the working group members added

update contact details

---

content/membership/members/toyota.md

toyota added

---

content/membership/members/bmw.md

bmw logo changed

---

content/membership/members/volkswagen.md

updated VW logo

---

content/membership/members/bosch.md

create member bosch

---

content/membership/members/itk.md

changed to service provider member

participation_levels name changed

---

content/membership/members/tuev.md

updated TÜV SÜD participation level

---

content/membership/members/volkswagen.md

updated VW GoA participation level

---

content/membership/members/itk.md

updated itk

---

content/membership/members/itk.md

added bosch member id to itk
Signed-off-by Maximilian Kraus "maximilian.kraus@tuev-sued.de"

Updated itk member id

---

content/about/index.md

Signed-off-by: Tuan Duong Quang Tuan.DuongQuang@tuev-sued.de

Update index.md, Add link to charter

---

less/styles.less
package-lock.json
package.json

Added upgrade to Hugo to include fixes for featured story.
Fix #29
Signed-off-by: Martin Lowe <martin.lowe@eclipse-foundation.org>

Change Request Webpage Layout #29

---

config.toml
content/resources/_index.md
data/featuredstory.yml

- Changed two link forms in resources
- Add tab sim@openPASS to resources
- Link to installer HLRS added
- Misspelling corrected
Signed-off-by: Tuan Duong Quang <DuongQuang@tuev-sued.de>

Changes in sim@openPASS tab and installer link to HLRS

---

content/resources/_index.md

Glossary --> openPass -->openPass slave --> explanation updated
Signed-off-by: Maximilian Kraus maximilian.kraus@tuev-sued.de

updated index

---

layouts/shortcodes/page/objectives.html

line 55 writing error improved
Signed-off-by: Maximilian Kraus maximilian.kraus@tuev-sued.de

updated objectives

---

content/membership/members/volkswagen.md

Text for VW GoA added
Signed-off-by: Maximilian Kraus maximilian.kraus@tuev-sued.de

update VW GoA Text

---

config.toml
content/about/_index.md
layouts/shortcodes/members_list_no_nav.html

Fix #34
Signed-off-by: Martin Lowe <martin.lowe@eclipse-foundation.org>

Include "Members" into the "Working Group" tab #34

---

k8s/production.yml
k8s/staging.yml

Signed-off-by: Christopher Guindon <chris.guindon@eclipse-foundation.org>

initial commit of k8s configs

---

Jenkinsfile

Change-Id: I2ecef1bc77c3f8455eeb48c4da3e221823424009
Signed-off-by: Christopher Guindon <chris.guindon@eclipse-foundation.org>

Add jenkins file

---

content/resources/_index.md

changed framework into platform
Sigend-off-by Maximilian Kraus Maximilian.Kraus@tuev-sued.de

changed framework into platform

---

package-lock.json
package.json

Signed-off-by: Martin Lowe <martin.lowe@eclipse-foundation.org>

Update Hugo theme version to fix IE JS

---

package-lock.json
package.json

Fixes #88
Signed-off-by: Martin Lowe <martin.lowe@eclipse-foundation.org>

Featured Footer/story not working correctly in IE #88

---

config.toml
content/_index.md
data/featuredstory.yml
layouts/partials/footer_custom.html
layouts/shortcodes/home-newsletter.html
less/styles.less
package-lock.json
package.json

One of https://github.com/EclipseFdn/jquery-eclipsefdn-api/issues/16
Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

update theme to 0099, add custom footer and LESS
